# Generated by Django 5.0.6 on 2024-06-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIApp', '0005_alter_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
    ]
