# Generated by Django 5.0.6 on 2024-06-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIApp', '0006_alter_task_completed_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
