# Generated by Django 5.0.6 on 2024-06-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIApp', '0011_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default='No Description...'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
